# Indicates compatibility version with lifecycle
api = "0.8"

[buildpack]
description = "A Cloud Native Buildpack that installs starkli"
homepage = "https://github.com/amp-buildpacks/starknet"
id = "paketo-community/starknet"
keywords = ["cairo", "starkli"]
name = "Paketo Buildpack for Starkli"
sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
version = "2.4.3"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/paketo-community/starknet/blob/main/LICENSE"

[metadata]
include-files = ["LICENSE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
pre-package = "scripts/build.sh"


[[metadata.configurations]]
build = true
default = "0.2.3"
description = "the starkli version"
name = "BP_STARKLI_VERSION"

[[metadata.configurations]]
build = true
default = "musl"
description = "libc implementation: gnu or musl"
name = "BP_STARKLI_LIBC"

[[metadata.configurations]]
build = true
default = "/account/starkli.json"
description = "starknet account path "
name = "BP_STARKNET_ACCOUNT_PATH"

[[metadata.configurations]]
build = true
default = "/account/keystore.json"
description = "starknet keystore path"
name = "BP_STARKNET_KEYSTORE_PATH"

[[metadata.configurations]]
build = true
default = "123456"
description = "starknet  keystore password"
name = "BP_STARKNET_KEYSTOREPASSWORD"

[[metadata.configurations]]
build = true
default = ""
description = "starknet network rpc"
name = "BP_STARKNET_DEPLOY_CONSTRUCTOR_U256"
[[metadata.configurations]]
build = true
default = ""
description = "starknet network rpc"
name = "BP_STARKNET_DEPLOY_CONSTRUCTOR_U128"

[[metadata.configurations]]
build = true
default = "https://starknet-testnet.public.blastapi.io/rpc/v0_6"
description = "starknet network rpc"
name = "BP_STARKNET_NETWORK"

[[metadata.configurations]]
build = true
default = "false"
description = "deploy starknet contract "
name = "BP_STARKNET_DEPLOY"



[[metadata.dependencies]]
id = "starkli-musl"
name = "Starkli (musl libc)"
purl = "pkg:generic/starkli@0.2.3"
stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
uri = "https://github.com/xJonathanLEI/starkli/releases/download/v0.2.3/starkli-x86_64-unknown-linux-gnu.tar.gz"
version = "0.2.3"

[[metadata.dependencies]]
id = "starkli-gnu"
name = "Starkli (gnu libc)"
purl = "pkg:generic/starkli@0.2.3"
stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
uri = "https://github.com/xJonathanLEI/starkli/releases/download/v0.2.3/starkli-x86_64-unknown-linux-gnu.tar.gz"
version = "0.2.3"

[[metadata.dependencies.licenses]]
type = "MIT"
uri = "https://github.com/software-mansion/scarb/blob/main/LICENSE"

[[stacks]]
id = "*"
