# Indicates compatibility version with lifecycle
api = "0.8"

[buildpack]
description = "A buildpack for installing the appropriate Scarb application"
homepage = "https://github.com/paketo-community/starkli"
id = "paketo-community/starkli"
keywords = ["cairo", "starkli"]
name = "Paketo Buildpack for starkli"
sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
version = "0.1.0"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/paketo-community/scarb/blob/main/LICENSE"

[metadata]
include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "buildpack.toml"]
pre-package = "scripts/build.sh"

[[metadata.configurations]]
build = true
default = "goerli"
description = "mainnet,goerli,sepolia"
name = "BP_STARKNET_NETWORK"

[[metadata.configurations]]
build = true
default = "/path/to/keystore"
description = "To create a fresh keystore from scratch"
name = "BP_STARKNET_KEYSTORE_PATH"
[[metadata.configurations]]
build = true
default = "/path/to/account"
description = "To create a fresh keystore from scratch"
name = "BP_STARKNET_ACCOUNT_PATH"

[[metadata.dependencies]]
id = "starkli-musl"
name = "Starkli"
purl = "pkg:generic/starkli@0.2.3"
stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
uri = "https://github.com/xJonathanLEI/starkli/releases/download/v0.2.3/starkli-x86_64-unknown-linux-musl.tar.gz"
version = "0.2.3"

[[metadata.dependencies.licenses]]
type = "MIT"
uri = "https://github.com/software-mansion/scarb/blob/main/LICENSE"

[[stacks]]
id = "*"
